-- Create a read-only (select) user to view database state in running application.
DROP USER IF EXISTS guest;
CREATE USER guest PASSWORD 'guest';

-- The default schema in H2 is 'PUBLIC'.
GRANT SELECT ON SCHEMA PUBLIC TO guest;

DROP SEQUENCE IF EXISTS TRADE_ORDER_ID_SEQUENCE;
CREATE SEQUENCE TRADE_ORDER_ID_SEQUENCE
    START WITH 111100
    INCREMENT BY 100;

DROP TABLE IF EXISTS TRADE_ORDER CASCADE;
CREATE TABLE TRADE_ORDER
(
    ORDER_ID           IDENTITY     NOT NULL COMMENT 'Order Id' PRIMARY KEY,
    STOCK_TICKER       VARCHAR(6)   NOT NULL COMMENT 'Ticker code of the stock',
    PRICE              NUMERIC(20, 4)      NOT NULL COMMENT 'Price of the stock',
    QUANTITY           BIGINT       NOT NULL COMMENT 'Quantity ordered',
    TYPE               VARCHAR(5)   NOT NULL COMMENT 'Status of the order.' CHECK REGEXP_LIKE(TYPE, '^(BUY|SELL)$'),
    STATUS             VARCHAR(20)  NOT NULL COMMENT 'Status of the order.',
    USER_ID            BIGINT  NOT NULL COMMENT 'User Id.'

);
COMMENT ON TABLE TRADE_ORDER IS 'ORDER TABLE';

DROP SEQUENCE IF EXISTS HOLDING_ID_SEQUENCE;
CREATE SEQUENCE HOLDING_ID_SEQUENCE
    START WITH 111100
    INCREMENT BY 100;

DROP TABLE IF EXISTS HOLDING CASCADE;
CREATE TABLE HOLDING
(
    HOLDING_ID           IDENTITY     NOT NULL COMMENT 'HOLDING Id' PRIMARY KEY,
    STOCK_TICKER       VARCHAR(6)   NOT NULL COMMENT 'Ticker code of the stock',
    PURCHASE_PRICE     NUMERIC(20, 4)      NOT NULL COMMENT 'Price of the stock',
    QUANTITY           BIGINT       NOT NULL COMMENT 'Quantity ordered',
    USER_ID            BIGINT  NOT NULL COMMENT 'User Id.'
);

COMMENT ON TABLE HOLDING IS 'HOLDING TABLE';